

### Get authors
GET /publishers HTTP/1.1
Host: localhost:8080
Accept: application/json


### Feel free to compare the results against localhost:8081 to see the effect of our ACL
GET /publishers HTTP/1.1
Host: localhost:8081
Accept: application/json

### Get authors
GET /publishers/80553ae1-2ef8-4adf-8fa8-d551684a9ea3 HTTP/1.1
Host: localhost:8081
Accept: application/json